'use client';
import { useMemo, useState } from 'react';
import { CommentaryEditor, type CommentaryView } from '@/components/cost-fluctuation/governance/commentary-editor';
import { CommentaryStatusBadge } from '@/components/cost-fluctuation/governance/commentary-status-badge';
import { governancePermissions, isCommentaryTarget } from '@/lib/cost-fluctuation/governance/presentation';

type PeriodOption = { id: number; companyCode: string; fiscalYear: number; fiscalPeriod: number };
type Row = { key: string; label: string; nodeType: string; varianceAmount: string; variancePercent: string|null; materialityStatus: string; children?: Row[] };
type Overlay = { kind?: string; hierarchy?: Row[]; status?: string; comparisonLabel?: string; commentaries?: CommentaryView[]; analysisLineageKey?: string; error?: string };
const flatten=(rows:Row[],depth=0):Array<Row&{depth:number}>=>rows.flatMap(row=>[{...row,depth},...flatten(row.children??[],depth+1)]);

export default function FluctuationWorkflow({ periodOptions, role }: { periodOptions: PeriodOption[]; role: string }) {
  const [companyCode,setCompanyCode]=useState(''),[periodId,setPeriodId]=useState(''),[comparison,setComparison]=useState('MOM'),[selected,setSelected]=useState(''),[data,setData]=useState<Overlay|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
  const permissions=governancePermissions(role);
  const companies=useMemo(()=>[...new Set(periodOptions.map(p=>p.companyCode))].sort(),[periodOptions]);
  const companyPeriods=useMemo(()=>periodOptions.filter(p=>p.companyCode===companyCode),[companyCode,periodOptions]);
  const reset=()=>{setData(null);setSelected('');setMessage('');};
  async function load(){setLoading(true);setMessage('');try{const response=await fetch(`/api/cost-fluctuation/commentary?periodId=${periodId}&comparison=${comparison}`);const body=await response.json();setData(body);if(!response.ok)setMessage(body.error??'Unable to load analysis.');}finally{setLoading(false);}}
  async function action(kind:'draft'|'submit'|'return'|'review',payload?:string){const current=data?.commentaries?.find(item=>item.analysisKey===selected);const config=kind==='draft'?{path:'/api/cost-fluctuation/commentary/draft',body:{periodId:Number(periodId),comparisonType:comparison,analysisKey:selected,reason:payload}}:{path:`/api/cost-fluctuation/commentary/${current?.id}/${kind}`,body:kind==='return'||kind==='review'?{reviewerNote:payload}:{}};setLoading(true);setMessage('');try{const response=await fetch(config.path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(config.body)});const body=await response.json();if(!response.ok){setMessage(body.error?.toLowerCase().includes('stale')?'This commentary belongs to an old lineage and was not reused. Reload the current analysis and create a new draft for its exact context.':body.error??'Action failed.');return;}await load();setMessage(`${kind[0].toUpperCase()+kind.slice(1)} completed.`);}finally{setLoading(false);}}
  const current=data?.commentaries?.find(item=>item.analysisKey===selected);
  return <section className="space-y-5">
    <div className="rounded-xl border bg-white p-5"><div className="flex flex-wrap gap-3"><select className="min-w-48 rounded border px-3 py-2" value={companyCode} onChange={e=>{setCompanyCode(e.target.value);setPeriodId(String(periodOptions.find(p=>p.companyCode===e.target.value)?.id??''));reset();}}><option value="">Select company</option>{companies.map(code=><option key={code}>{code}</option>)}</select><select className="min-w-52 rounded border px-3 py-2" value={periodId} disabled={!companyCode} onChange={e=>{setPeriodId(e.target.value);reset();}}><option value="">Select finalized period</option>{companyPeriods.map(p=><option key={p.id} value={p.id}>{p.fiscalYear}/{String(p.fiscalPeriod).padStart(2,'0')}</option>)}</select><select className="rounded border px-3 py-2" value={comparison} onChange={e=>{setComparison(e.target.value);reset();}}><option>MOM</option><option>YOY</option><option>YTD</option></select><button className="rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50" onClick={load} disabled={loading||!periodId}>{loading?'Loading…':'Load governance context'}</button></div><p className="mt-3 text-xs text-slate-500">Only finalized Cost Structure periods are selectable. COMPANY and ANALYSIS_BASIS are context and never commentary targets.</p></div>
    {message&&<p role="status" className="rounded border bg-slate-50 p-3 text-sm">{message}</p>}
    {data?.status==='UNAVAILABLE'&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><strong>Comparison unavailable</strong><p className="text-sm">{data.comparisonLabel}. Missing history is not treated as zero and no commentary is required for this comparison.</p></div>}
    {data?.status==='AVAILABLE'&&<><div className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p>{data.comparisonLabel}: <strong>AVAILABLE</strong></p><a href={`/cost-fluctuation/review?periodId=${periodId}`} className="text-sm font-medium text-blue-700">Open period readiness →</a></div><p className="mt-1 text-xs text-slate-500">Lineage: <code>{data.analysisLineageKey?.slice(0,16)}…</code>. Commentary is loaded only for this exact run/upload/rule/comparison lineage.</p></div><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_380px]"><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Analytical hierarchy</th><th>Variance</th><th>Variance %</th><th>Materiality</th><th>Commentary</th></tr></thead><tbody>{flatten(data.hierarchy??[]).map(row=>{const target=isCommentaryTarget(row.nodeType),commentary=data.commentaries?.find(item=>item.analysisKey===row.key);return <tr key={row.key} className={`border-t ${target?'cursor-pointer hover:bg-blue-50': 'bg-slate-50/60'}`} onClick={()=>target&&setSelected(row.key)}><td className="p-3" style={{paddingLeft:12+row.depth*18}}><span>{row.label}</span>{row.nodeType==='ANALYSIS_BASIS'&&<span className="ml-2 rounded bg-violet-100 px-2 py-0.5 text-xs text-violet-800">basis context</span>}<span className="ml-2 text-xs text-slate-400">{row.nodeType}</span></td><td>{row.varianceAmount}</td><td>{row.variancePercent??'N/M'}</td><td><span className={row.materialityStatus==='NOT_CONFIGURED'?'font-semibold text-red-700':''}>{row.materialityStatus}</span></td><td>{target?<CommentaryStatusBadge status={commentary?.status??(row.materialityStatus==='REQUIRES_EXPLANATION'?'OPEN':'—')}/>:<span className="text-slate-400">Context only</span>}</td></tr>})}</tbody></table></div>{selected?<CommentaryEditor key={`${selected}:${current?.id??'new'}:${current?.status??'OPEN'}`} analysisKey={selected} commentary={current} permissions={permissions} busy={loading} onAction={action}/>:<div className="rounded-xl border border-dashed p-5 text-sm text-slate-500">Select a Cost Group, Nature, COA, or Calculated Item. GHOPO and DERIV remain separate because their basis-qualified keys are never deduplicated by period.</div>}</div></>}
    {!periodOptions.length&&<p className="rounded border border-amber-200 bg-amber-50 p-4">No FINALIZED Cost Structure period is available.</p>}
  </section>;
}
