export const PHASE_I_READ_ROLES = ['ADMIN_SYSTEM','STAFF_ACCOUNTING','SUPERVISOR_ACCOUNTING','AUDITOR_INTERNAL','STAFF_PRODUCTION'] as const;
export const PHASE_I_PREPARE_ROLES = ['ADMIN_SYSTEM','STAFF_ACCOUNTING'] as const;
export const PHASE_I_REVIEW_ROLES = ['ADMIN_SYSTEM','SUPERVISOR_ACCOUNTING'] as const;
export const PHASE_I_ADMIN_ROLES = ['ADMIN_SYSTEM'] as const;
