import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { completeStoredUpload, DuplicateUploadError } from './completion-service';
import { createStorageKey, MAX_WORKBOOK_BYTES, signPendingUpload, validateWorkbookDeclaration, verifyPendingUpload } from './uploads';
import type { ParsedWorkbook } from './parsers';
import { isCostStructurePrepareRole } from './permissions';

const parsed:ParsedWorkbook={rows:[{logicalSourceCode:'TB',originalSheetName:'TB',sourceRowNumber:2,coaCodeRaw:'001',descriptionRaw:'Test',amountRaw:'1',amount:'1',sourceGroupRaw:null,rawDataJson:{}}],issues:[],sources:[{code:'TB',sheetName:'TB',rowCount:1}]};
type Upload={version:number;hash:string;active:boolean;rows:number;mappingStatus:string;storageKey?:string};
function fake(initial:Upload[]=[]){let uploads=structuredClone(initial),removed=false,failAfterRows=false;const calculations={runs:0,actuals:0,results:0};const bytes=new TextEncoder().encode('different workbook');return {bytes,get uploads(){return uploads},get removed(){return removed},calculations,failAfterPartialRows(){failAfterRows=true},deps:{download:async()=>bytes,remove:async()=>{removed=true},findDuplicate:async(_period:number,hash:string)=>uploads.find(x=>x.hash===hash)||null,parse:async()=>parsed,persistAtomically:async({hash}:{hash:string})=>{const snapshot=structuredClone(uploads);try{uploads.forEach(x=>x.active=false);const next={version:Math.max(0,...uploads.map(x=>x.version))+1,hash,active:false,rows:parsed.rows.length,mappingStatus:'UNMAPPED'};uploads.push(next);if(failAfterRows)throw new Error('source row chunk failed');next.active=true;return next;}catch(error){uploads=snapshot;throw error;}}}}}

describe('Phase C completion invariants',()=>{
  it('rejects an exact duplicate for the period and removes the replay object',async()=>{const f=fake();const hash=await crypto.subtle.digest('SHA-256',f.bytes);f.uploads.push({version:1,hash:Buffer.from(hash).toString('hex'),active:true,rows:1,mappingStatus:'UNMAPPED'});await assert.rejects(()=>completeStoredUpload({periodId:1,objectKey:'controlled',expectedSize:f.bytes.length,companyCode:'2000'},f.deps),DuplicateUploadError);assert.equal(f.uploads.length,1);assert.equal(f.removed,true)});
  it('does not delete the active object when the same completion context is replayed',async()=>{const f=fake();const hash=Buffer.from(await crypto.subtle.digest('SHA-256',f.bytes)).toString('hex');f.uploads.push({version:1,hash,active:true,rows:1,mappingStatus:'UNMAPPED',storageKey:'controlled'});await assert.rejects(()=>completeStoredUpload({periodId:1,objectKey:'controlled',expectedSize:f.bytes.length,companyCode:'2000'},f.deps),DuplicateUploadError);assert.equal(f.removed,false)});
  it('creates the next version and deactivates the previous active upload',async()=>{const f=fake([{version:1,hash:'old',active:true,rows:1,mappingStatus:'UNMAPPED'}]);await completeStoredUpload({periodId:1,objectKey:'controlled',expectedSize:f.bytes.length,companyCode:'2000'},f.deps);assert.deepEqual(f.uploads.map(x=>[x.version,x.active]),[[1,false],[2,true]]);assert.equal(f.uploads[1].mappingStatus,'UNMAPPED');assert.deepEqual(f.calculations,{runs:0,actuals:0,results:0})});
  it('failed or partial persistence cannot activate a candidate and cleans storage',async()=>{const f=fake([{version:1,hash:'old',active:true,rows:1,mappingStatus:'UNMAPPED'}]);f.failAfterPartialRows();await assert.rejects(()=>completeStoredUpload({periodId:1,objectKey:'controlled',expectedSize:f.bytes.length,companyCode:'2000'},f.deps));assert.deepEqual(f.uploads.map(x=>x.active),[true]);assert.equal(f.uploads.length,1);assert.equal(f.removed,true)});
  it('parser failure leaves the previous upload active and removes the orphan',async()=>{const f=fake([{version:1,hash:'old',active:true,rows:1,mappingStatus:'UNMAPPED'}]);f.deps.parse=async()=>{throw new Error('unreadable')};await assert.rejects(()=>completeStoredUpload({periodId:1,objectKey:'controlled',expectedSize:f.bytes.length,companyCode:'2000'},f.deps));assert.equal(f.uploads[0].active,true);assert.equal(f.removed,true)});
});

describe('upload boundary security',()=>{
  it('generates a sanitized controlled path that traversal cannot escape',()=>{const key=createStorageKey('../2000',2026,1,'../../payroll.xlsx','../token');assert.match(key,/^cost-structure\/2000\/2026\/01\/token-payroll\.xlsx$/);assert.equal(key.includes('..'),false)});
  it('rejects oversized and unsupported declarations',()=>{assert.match(validateWorkbookDeclaration('data.xlsx',MAX_WORKBOOK_BYTES+1)!,/50 MB/);assert.match(validateWorkbookDeclaration('data.xls',10)!,/xlsx/)});
  it('detects tampering of init metadata, object key, and uploader identity',()=>{const old=process.env.AUTH_SECRET;process.env.AUTH_SECRET='unit-test-secret';const value={companyId:1,companyCode:'2000',fiscalYear:2026,fiscalPeriod:1,fileName:'a.xlsx',fileSize:10,objectKey:'cost-structure/2000/2026/01/id-a.xlsx',userId:7,expiresAt:Date.now()+60_000};const token=signPendingUpload(value);assert.deepEqual(verifyPendingUpload(token),value);const [body,sig]=token.split('.');const changed={...value,companyCode:'7000',userId:8,objectKey:'evil'};const tampered=`${Buffer.from(JSON.stringify(changed)).toString('base64url')}.${sig}`;assert.equal(verifyPendingUpload(tampered),null);assert.equal(verifyPendingUpload(`${body}.broken`),null);if(old===undefined)delete process.env.AUTH_SECRET;else process.env.AUTH_SECRET=old});
  it('rejects non-PREPARE roles',()=>{assert.equal(isCostStructurePrepareRole('SUPERVISOR_ACCOUNTING'),false);assert.equal(isCostStructurePrepareRole('AUDITOR_INTERNAL'),false);assert.equal(isCostStructurePrepareRole('STAFF_ACCOUNTING'),true)});
});
