'use client';
import { useEffect, useMemo, useState } from 'react';
import { governancePermissions, isCommentaryTarget } from '@/lib/cost-fluctuation/governance/presentation';

type Period = { id:number; companyCode:string; fiscalYear:number; fiscalPeriod:number };
type Node = { key:string; nodeType:string; materialityStatus:string; children?:Node[] };
type Overlay = { status?:string; comparisonLabel?:string; hierarchy?:Node[]; commentaries?:Array<{analysisKey:string;status:string}>; error?:string };
type Readiness = { ready:boolean; blockers:string[]; availableComparisons:number; review?:{reviewStatus:string;reviewedAt?:string;note?:string|null}|null; error?:string };
const TYPES=['MOM','YOY','YTD'] as const;
const flat=(nodes:Node[]):Node[]=>nodes.flatMap(node=>[node,...flat(node.children??[])]);

export function ReviewReadinessPanel({ periods, role, initialPeriodId }: { periods:Period[];role:string;initialPeriodId?:string }) {
  const [periodId,setPeriodId]=useState(initialPeriodId??''),[overlays,setOverlays]=useState<Record<string,Overlay>>({}),[readiness,setReadiness]=useState<Readiness|null>(null),[loading,setLoading]=useState(false),[note,setNote]=useState(''),[message,setMessage]=useState('');
  const permissions=governancePermissions(role);
  async function load(){if(!periodId)return;setLoading(true);setMessage('');try{const [review,...results]=await Promise.all([fetch(`/api/cost-fluctuation/review?periodId=${periodId}`).then(r=>r.json()),...TYPES.map(type=>fetch(`/api/cost-fluctuation/commentary?periodId=${periodId}&comparison=${type}`).then(r=>r.json()))]);setReadiness(review);setOverlays(Object.fromEntries(TYPES.map((type,index)=>[type,results[index]])));}finally{setLoading(false);}}
  useEffect(()=>{if(initialPeriodId)void load();/* initial deep-link only */},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const metrics=useMemo(()=>{const targetRows=TYPES.flatMap(type=>{const overlay=overlays[type];if(overlay?.status!=='AVAILABLE')return[];const status=new Map(overlay.commentaries?.map(c=>[c.analysisKey,c.status]));return flat(overlay.hierarchy??[]).filter(n=>isCommentaryTarget(n.nodeType)).map(n=>({materiality:n.materialityStatus,commentary:status.get(n.key)??'OPEN'}));});const count=(value:string)=>targetRows.filter(row=>row.commentary===value).length;return {configured:targetRows.filter(r=>!['NOT_CONFIGURED','NOT_EVALUABLE'].includes(r.materiality)).length,notConfigured:targetRows.filter(r=>r.materiality==='NOT_CONFIGURED').length,notEvaluable:targetRows.filter(r=>r.materiality==='NOT_EVALUABLE').length,material:targetRows.filter(r=>r.materiality==='REQUIRES_EXPLANATION').length,draft:count('DRAFT'),submitted:count('SUBMITTED'),returned:count('RETURNED'),reviewed:count('REVIEWED')};},[overlays]);
  async function complete(){setLoading(true);setMessage('');try{const response=await fetch('/api/cost-fluctuation/review/complete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({periodId:Number(periodId),note})});const body=await response.json();if(!response.ok){setMessage(body.error??'Completion failed.');return;}setMessage('Period analytical review completed. Cost Structure lifecycle was not changed.');await load();}finally{setLoading(false);}}
  const blockerText=(blocker:string)=>blocker==='AVAILABLE'?'All MoM, YoY, and YTD comparisons are unavailable. At least one comparison must be available.':blocker==='NOT_CONFIGURED'?'At least one target has no applicable materiality rule (NOT_CONFIGURED).':blocker==='NOT_EVALUABLE'?'At least one configured target cannot be evaluated.':blocker==='FINALIZED'?'Cost Structure period is not FINALIZED.':blocker.includes(':')?`${blocker}: required exact-lineage commentary is not REVIEWED.`:blocker;
  return <div className="space-y-5"><div className="flex flex-wrap gap-3 rounded-xl border bg-white p-5"><select value={periodId} onChange={e=>{setPeriodId(e.target.value);setReadiness(null);setOverlays({});}} className="min-w-64 rounded border p-2"><option value="">Select finalized period</option>{periods.map(p=><option key={p.id} value={p.id}>{p.companyCode} · {p.fiscalYear}/{String(p.fiscalPeriod).padStart(2,'0')}</option>)}</select><button disabled={!periodId||loading} onClick={load} className="rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50">{loading?'Checking…':'Check readiness'}</button></div>{message&&<p role="status" className="rounded border bg-slate-50 p-3">{message}</p>}
  {readiness&&<><section className="rounded-xl border bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">Analytical review status</p><h2 className="text-xl font-semibold">{readiness.review?.reviewStatus??'OPEN'}</h2></div><span className={`rounded-full px-3 py-1 text-sm font-semibold ${readiness.ready?'bg-emerald-100 text-emerald-800':'bg-red-100 text-red-800'}`}>{readiness.ready?'READY':'BLOCKED'}</span></div></section>
  <section className="grid gap-3 md:grid-cols-3">{TYPES.map(type=>{const overlay=overlays[type];return <div key={type} className="rounded-xl border bg-white p-4"><strong>{type}</strong><p className={`mt-2 text-sm font-semibold ${overlay?.status==='AVAILABLE'?'text-emerald-700':'text-amber-700'}`}>{overlay?.status??'UNKNOWN'}</p><p className="mt-1 text-xs text-slate-500">{overlay?.comparisonLabel}</p>{overlay?.status==='UNAVAILABLE'&&<p className="mt-2 text-xs">Unavailable does not mean zero and does not individually block.</p>}</div>})}</section>
  <section className="grid grid-cols-2 gap-3 md:grid-cols-5">{Object.entries(metrics).map(([label,value])=><div key={label} className="rounded-xl border bg-white p-4"><p className="text-xs uppercase text-slate-500">{label.replace(/([A-Z])/g,' $1')}</p><p className="text-2xl font-semibold">{value}</p></div>)}</section>
  <section className={`rounded-xl border p-5 ${readiness.blockers.length?'border-red-200 bg-red-50':'border-emerald-200 bg-emerald-50'}`}><h2 className="font-semibold">{readiness.blockers.length?'Why can’t this period be completed?':'All readiness controls passed'}</h2>{readiness.blockers.length?<ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{readiness.blockers.map((blocker,index)=><li key={`${blocker}-${index}`}>{blockerText(blocker)}</li>)}</ul>:<p className="mt-2 text-sm">At least one comparison is available, materiality is configured/evaluable, and every required exact-lineage commentary is REVIEWED.</p>}</section>
  <section className="rounded-xl border bg-white p-5"><label className="block text-sm font-medium">Completion note (optional)<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={5000} disabled={!permissions.canReview||readiness.review?.reviewStatus==='COMPLETED'} className="mt-1 block min-h-20 w-full rounded border p-3 disabled:bg-slate-50"/></label><button disabled={!permissions.canReview||!readiness.ready||loading||readiness.review?.reviewStatus==='COMPLETED'} onClick={complete} className="mt-3 rounded bg-emerald-700 px-4 py-2 text-white disabled:opacity-50">Complete analytical review</button>{!permissions.canReview&&<p className="mt-2 text-sm text-slate-500">Only ADMIN_SYSTEM and SUPERVISOR_ACCOUNTING can complete review.</p>}</section></>}
  </div>;
}
