import test from 'node:test'; import assert from 'node:assert/strict'; import { Prisma } from '@prisma/client';
import { financial, variance } from './math'; import { resolveComparisonMonths } from './periods';
import { buildFinalizedMonthlySnapshot, FluctuationIntegrityError } from './snapshot'; import { aggregateSnapshots } from './aggregate'; import { compareSnapshots } from './compare';
import type { PersistedLine, PersistedPeriod, PersistedResult, PersistedSourceRow } from './types';
const d=(v:Prisma.Decimal.Value)=>new Prisma.Decimal(v); const groups={HPP:1,ADUM:2,PASAR:3} as const;
const names:Record<string,string>={H01:'Bahan Baku',H16:'Selisih Persediaan',N01:'Bahan Penolong',N02:'Bahan Bakar',OA:'OA'};
function source(uploadId:number,code:string,rows:Array<[string,string]>):PersistedSourceRow[]{return rows.map(([label,amount],i)=>({id:i+1,uploadId,logicalSourceCode:code,sourceRowNumber:i+1,rawDataJson:{COLUMN_1:label,COLUMN_2:amount}}));}
function period(companyCode:'2000'|'7000',year=2026,month=7):PersistedPeriod{
 const codes:Array<keyof typeof groups>=companyCode==='2000'?['ADUM','PASAR']:['HPP','ADUM','PASAR']; const amounts:Record<keyof typeof groups,string>=companyCode==='2000'?{HPP:'0',ADUM:'107844157911',PASAR:'16487761095'}:{HPP:'413169722810',ADUM:'11667383975',PASAR:'81641587070'};
 const results:PersistedResult[]=[]; const actualLines:PersistedLine[]=[]; let natureId=10;
 for(const code of codes){const natureCode=code==='HPP'?'H16':code==='ADUM'?'N01':'N02'; const amount=d(amounts[code]); results.push({costGroupId:groups[code],natureId:null,resultCode:`TOTAL_${code}`,resultType:'TOTAL',amount,costGroup:{code,name:code,displayOrder:groups[code]},nature:null},{costGroupId:groups[code],natureId,resultCode:'NATURE_TOTAL',resultType:'NATURE',amount,costGroup:{code,name:code,displayOrder:groups[code]},nature:{code:natureCode,name:names[natureCode],displayOrder:1}}); actualLines.push({costGroupId:groups[code],natureId,coaId:100+groups[code],lineType:'COA',finalAmount:amount,ruleCode:null,coa:{coaCode:`COA${code}`,coaDescription:code}}); natureId++;if(code==='PASAR'){results.push({costGroupId:groups.PASAR,natureId,resultCode:'NATURE_TOTAL',resultType:'NATURE',amount:d(0),costGroup:{code,name:code,displayOrder:groups[code]},nature:{code:'OA',name:'OA',displayOrder:2}});natureId++;}}
 const total=codes.reduce((s,code)=>s.add(amounts[code]),d(0)); results.push({costGroupId:null,natureId:null,resultCode:'TOTAL_COMPANY',resultType:'TOTAL',amount:total,costGroup:null,nature:null}); const id=year*100+month; const uploadId=id+2;
 const auditCode=companyCode==='2000'?'AUDIT_SI':'AUDIT_GHOPO'; const auditRows=codes.flatMap(code=>[[code==='HPP'?'Beban Pokok Penjualan':code==='ADUM'?'UMUM & ADMINISTRASI':'PEMASARAN',''],[names[code==='HPP'?'H16':code==='ADUM'?'N01':'N02'],d(amounts[code]).div(1000).toString()],[code==='HPP'?'Total HPP':code==='ADUM'?'Total Adum':'Total Perniagaan',d(amounts[code]).div(1000).toString()]] as Array<[string,string]>);
 const deriv=source(uploadId,'AUDIT_DERIV',[['Beban Pokok Penjualan',''],['Selisih Persediaan','4571043.173'],['Total HPP','4571043.173'],['UMUM & ADMINISTRASI',''],['Bahan Penolong','0'],['Total Adum','0'],['PEMASARAN',''],['Bahan Bakar','1488906.545'],['Total Perniagaan','1488906.545'],['OA','368191.098']]);
 return{id,companyId:companyCode==='2000'?20:70,companyCode,fiscalYear:year,fiscalPeriod:month,status:'FINALIZED',activeCalculationRunId:id+1,activeRun:{id:id+1,periodId:id,uploadId,status:'SUCCESS',isActive:true,ruleSetVersion:`ENGINE1_${companyCode}_V${companyCode==='2000'?2:1}`,results,actualLines,sourceRows:[...source(uploadId,auditCode,auditRows),...(companyCode==='7000'?deriv:[])]}};
}
test('Company 2000 exposes exactly SI with golden total and basis-qualified paths',()=>{const s=buildFinalizedMonthlySnapshot(period('2000'))!;assert.equal(s.amount.toFixed(2),'124331919006.00');assert.deepEqual(s.bases.map(b=>b.code),['SI']);assert.ok(!JSON.stringify(s).includes('DERIV'));assert.ok(!s.bases[0].groups.some(g=>g.code==='HPP'));assert.match(s.bases[0].groups[0].natures[0].items[0].key,/^basis:SI:group:\d+:nature:\d+:coa:\d+$/);});
test('SI independent parity failure rejects finalized data',()=>{const p=period('2000');(p.activeRun!.sourceRows[1].rawDataJson as Record<string,string>).COLUMN_2='1';assert.throws(()=>buildFinalizedMonthlySnapshot(p),FluctuationIntegrityError);});
test('Company 7000 separates GHoPO and DERIV and produces composite golden',()=>{const s=buildFinalizedMonthlySnapshot(period('7000'))!;assert.deepEqual(s.bases.map(b=>b.code),['GHOPO','DERIV']);assert.equal(s.bases[0].amount.toFixed(2),'506478693855.00');assert.equal(s.bases[1].amount.toFixed(2),'6428140816.00');assert.equal(s.amount.toFixed(2),'512906834671.00');const deriv=s.bases[1];assert.equal(deriv.groups.find(g=>g.code==='HPP')!.amount.toFixed(2),'4571043173.00');assert.equal(deriv.groups.find(g=>g.code==='PASAR')!.amount.toFixed(2),'1857097643.00');assert.notEqual(s.bases[0].groups[0].key,deriv.groups[0].key);});
test('DERIV missing and control mismatches fail rather than becoming zero',()=>{const missing=period('7000');missing.activeRun!.sourceRows=missing.activeRun!.sourceRows.filter(r=>r.logicalSourceCode!=='AUDIT_DERIV');assert.throws(()=>buildFinalizedMonthlySnapshot(missing),/AUDIT_DERIV source is missing/);const mismatch=period('7000');const total=mismatch.activeRun!.sourceRows.find(r=>r.logicalSourceCode==='AUDIT_DERIV'&&(r.rawDataJson as Record<string,string>).COLUMN_1==='Total HPP')!;(total.rawDataJson as Record<string,string>).COLUMN_2='0';assert.throws(()=>buildFinalizedMonthlySnapshot(mismatch),/leaf sum/);});
test('financial normalization removes only sub-cent Excel residue',()=>{assert.equal(financial('93152232023.316').toString(),'93152232023.32');assert.equal(financial('41023853211.684').toString(),'41023853211.68');});
test('MoM January, YoY and no-partial YTD period contracts remain stable',()=>{assert.deepEqual(resolveComparisonMonths({fiscalYear:2026,fiscalPeriod:1},'MOM').comparison,[{fiscalYear:2025,fiscalPeriod:12}]);assert.deepEqual(resolveComparisonMonths({fiscalYear:2026,fiscalPeriod:7},'YOY').comparison,[{fiscalYear:2025,fiscalPeriod:7}]);assert.equal(resolveComparisonMonths({fiscalYear:2026,fiscalPeriod:7},'YTD').comparison.length,7);});
test('YTD aggregation preserves basis separation and all lineage',()=>{const one=buildFinalizedMonthlySnapshot(period('7000',2026,1))!,two=buildFinalizedMonthlySnapshot(period('7000',2026,2))!;const ytd=aggregateSnapshots([one,two]);assert.deepEqual(ytd.bases.map(b=>b.code),['GHOPO','DERIV']);assert.equal(ytd.lineage.length,4);assert.equal(ytd.amount.toFixed(2),'1025813669342.00');});
test('NM and signed contribution/PARENT_ZERO semantics remain stable',()=>{assert.equal(variance(d(10),d(0)).status,'NM');const s=buildFinalizedMonthlySnapshot(period('2000'))!;const compared=compareSnapshots(s,s);assert.equal(compared.children![0].contributionStatus,'PARENT_ZERO');assert.equal(compared.children![0].contributionBasis,'ANALYSIS_BASIS_TO_COMPANY');assert.equal(compared.children![0].children![0].contributionBasis,'COST_GROUP_TO_ANALYSIS_BASIS');});
test('inactive, superseded, failed, and unrelated upload rows cannot supply a basis',()=>{for(const mutate of [(p:PersistedPeriod)=>p.activeRun!.isActive=false,(p:PersistedPeriod)=>p.activeRun!.status='FAILED',(p:PersistedPeriod)=>p.activeCalculationRunId=999]){const p=period('7000');mutate(p);assert.throws(()=>buildFinalizedMonthlySnapshot(p),/lineage/);}const p=period('7000');p.activeRun!.sourceRows.push(...source(999,'AUDIT_DERIV',[['Unknown','999']]));assert.equal(buildFinalizedMonthlySnapshot(p)!.amount.toFixed(2),'512906834671.00');});
