'use client';
import { ChevronDown, ChevronRight, FunctionSquare } from 'lucide-react';
import { useMemo, useState } from 'react';
import { formatIdr, formatPercent } from './formatting';
import { allExpandableKeys, commentaryStatus, flattenVisible } from './tree-utils';
import type { AnalysisNode, Commentary } from './types';

const badge:Record<string,string>={COMPANY:'bg-slate-800 text-white',ANALYSIS_BASIS:'bg-indigo-100 text-indigo-800',COST_GROUP:'bg-blue-100 text-blue-800',NATURE:'bg-emerald-100 text-emerald-800',COA:'bg-slate-100 text-slate-700',CALCULATED_ITEM:'bg-amber-100 text-amber-800'};
export function AnalysisTreeTable({ nodes, commentaries=[], onCommentary }: { nodes:AnalysisNode[]; commentaries?:Commentary[]; onCommentary?:(node:AnalysisNode)=>void }) {
  const defaults=useMemo(()=>new Set(allExpandableKeys(nodes).filter(key=>!key.includes(':nature:'))),[nodes]);
  const [expanded,setExpanded]=useState(defaults);
  const rows=flattenVisible(nodes,expanded); const statuses=new Map(commentaries.map(x=>[x.analysisKey,x.status]));
  const toggle=(key:string)=>setExpanded(old=>{const next=new Set(old);if(next.has(key))next.delete(key);else next.add(key);return next});
  if(!rows.length)return <div className="rounded-xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">Tidak ada baris yang cocok dengan filter.</div>;
  return <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="min-w-[1320px] w-full text-sm"><thead className="sticky top-0 z-10 bg-slate-100 text-left text-xs uppercase tracking-wide text-slate-600"><tr>{['Analysis Item','Current','Comparison','Variance Rp','Variance %','Contribution %','Materiality','Commentary'].map((x,i)=><th key={x} className={`${i>0?'text-right':''} px-3 py-3`}>{x}</th>)}</tr></thead><tbody>{rows.map(row=>{const total=['COMPANY','ANALYSIS_BASIS','COST_GROUP'].includes(row.nodeType);return <tr key={row.key} className={`${total?'bg-slate-50 font-semibold':'bg-white'} border-t border-slate-100 hover:bg-blue-50/40`}><td className="px-3 py-3" style={{paddingLeft:12+row.depth*22}}><div className="flex items-center gap-2">{row.hasChildren?<button aria-label={`${expanded.has(row.key)?'Tutup':'Buka'} ${row.label}`} onClick={()=>toggle(row.key)}>{expanded.has(row.key)?<ChevronDown className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}</button>:<span className="w-4"/>}<span className={`rounded px-2 py-0.5 text-[10px] font-bold ${badge[row.nodeType]}`}>{row.nodeType==='ANALYSIS_BASIS'?row.code:row.nodeType.replace('_',' ')}</span>{row.nodeType==='CALCULATED_ITEM'&&<FunctionSquare className="h-4 w-4 text-amber-600"/>}<span>{row.label}</span>{row.nodeType==='COA'&&<span className="text-xs font-normal text-slate-500">({row.code})</span>}</div></td><Money value={row.currentAmount}/><Money value={row.comparisonAmount}/><Money value={row.varianceAmount} signed/><td className="px-3 py-3 text-right tabular-nums">{formatPercent(row.variancePercent,row.variancePercentStatus)}</td><td className="px-3 py-3 text-right tabular-nums">{formatPercent(row.contribution,row.contributionStatus)}</td><td className="px-3 py-3 text-right"><Status value={row.materialityStatus??'NOT_CONFIGURED'} context={!isTarget(row)}/></td><td className="px-3 py-3 text-right"><div className="flex items-center justify-end gap-2"><Status value={commentaryStatus(row,statuses)}/>{isTarget(row)&&<button type="button" className="rounded border border-blue-300 px-2 py-1 text-xs font-medium text-blue-700 hover:bg-blue-50" onClick={()=>onCommentary?.(row)}>{statuses.has(row.key)?'Lihat komentar':'Beri komentar'}</button>}</div></td></tr>})}</tbody></table></div>;
}
const isTarget=(n:AnalysisNode)=>!['COMPANY','ANALYSIS_BASIS'].includes(n.nodeType);
function Money({value,signed=false}:{value:string;signed?:boolean}){const negative=value.startsWith('-');return <td className={`px-3 py-3 text-right tabular-nums ${signed?(negative?'text-red-700':'text-emerald-700'):negative?'text-red-700':''}`}>{formatIdr(value)}</td>}
function Status({value,context=false}:{value:string;context?:boolean}){const text=context?'N/A':value.replaceAll('_',' ');const tone=value==='REQUIRES_EXPLANATION'||value==='OPEN'?'bg-amber-100 text-amber-800':value==='REVIEWED'||value==='NORMAL'?'bg-emerald-100 text-emerald-800':'bg-slate-100 text-slate-600';return <span className={`inline-block rounded-full px-2 py-1 text-[10px] font-bold ${tone}`}>{text}</span>}
