'use client';
import { AlertTriangle, Download, Info, ShieldAlert, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { AnalysisSummary } from './analysis-summary';
import { AnalysisToolbar } from './analysis-toolbar';
import { AnalysisTreeTable } from './analysis-tree-table';
import { collectOptions, filterTree } from './tree-utils';
import type { AnalysisResponse, Filters } from './types';
import type { AnalysisNode } from './types';
import { CommentaryEditor } from '../governance/commentary-editor';
import { governancePermissions } from '@/lib/cost-fluctuation/governance/presentation';
import { formatIdr, formatPercent } from './formatting';

type Period={id:number;companyCode:string;fiscalYear:number;fiscalPeriod:number}; const empty:Filters={group:'',nature:'',materialOnly:false,needsCommentary:false};
export default function AnalysisDashboard({periodOptions,role,currentUserId}:{periodOptions:Period[];role:string;currentUserId?:number}){
 const [company,setCompany]=useState('');const [periodId,setPeriodId]=useState('');const [comparison,setComparison]=useState('MOM');const [filters,setFilters]=useState(empty);const [data,setData]=useState<AnalysisResponse|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState<{message:string;kind:string}|null>(null);const [selected,setSelected]=useState<AnalysisNode|null>(null);const [message,setMessage]=useState('');
 const companies=useMemo(()=>[...new Set(periodOptions.map(x=>x.companyCode))].sort(),[periodOptions]);const periods=periodOptions.filter(x=>x.companyCode===company);const options=collectOptions(data?.hierarchy??[]);const visible=filterTree(data?.hierarchy??[],filters,data?.commentaries);
 const reset=()=>{setData(null);setError(null);setFilters(empty)};
 const load=async()=>{setLoading(true);setError(null);try{const response=await fetch(`/api/cost-fluctuation/commentary?periodId=${periodId}&comparison=${comparison}`);const body=await response.json() as AnalysisResponse;if(!response.ok)throw Object.assign(new Error(body.error??'Analisis tidak dapat dimuat.'),{kind:response.status===401||response.status===403?'auth':response.status===409&&body.code==='FLUCTUATION_INTEGRITY_ERROR'?'integrity':'server'});setData(body)}catch(reason){const e=reason as Error&{kind?:string};setError({message:e.message||'Koneksi ke server gagal.',kind:e.kind??'network'});setData(null)}finally{setLoading(false)}};
 const action=async(kind:'draft'|'submit'|'return'|'review',payload?:string)=>{const current=data?.commentaries?.find(item=>item.analysisKey===selected?.key);if(kind!=='draft'&&!current)return;setLoading(true);setMessage('');const path=kind==='draft'?'/api/cost-fluctuation/commentary/draft':`/api/cost-fluctuation/commentary/${current!.id}/${kind}`;const body=kind==='draft'?{periodId:Number(periodId),comparisonType:comparison,analysisKey:selected?.key,reason:payload}:{reviewerNote:payload};try{const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error??'Action failed.');await load();setMessage('Commentary berhasil diperbarui.')}catch(e){setMessage(e instanceof Error?e.message:'Action failed.')}finally{setLoading(false)}};
 const current=data?.commentaries?.find(item=>item.analysisKey===selected?.key);const permissions=governancePermissions(role);
 return <section className="space-y-4"><AnalysisToolbar companies={companies} company={company} periods={periods} periodId={periodId} comparison={comparison} filters={filters} groups={options.groups} natures={options.natures} loading={loading} onCompany={value=>{setCompany(value);setPeriodId(String(periodOptions.find(x=>x.companyCode===value)?.id??''));reset()}} onPeriod={value=>{setPeriodId(value);reset()}} onComparison={value=>{setComparison(value);reset()}} onFilters={setFilters} onLoad={load}/>
 {periodOptions.length===0&&<Notice icon="info" text="Belum ada periode Cost Structure berstatus FINALIZED."/>}
 {error&&<Notice icon={error.kind==='integrity'?'integrity':'error'} text={error.kind==='auth'?'Sesi Anda tidak memiliki akses atau telah berakhir. Silakan masuk kembali.':error.message}/>} 
 {data?.status==='UNAVAILABLE'&&<Notice icon="info" text={`${data.comparisonLabel??comparison} — Comparison period not available. Nilai historis tidak diperlakukan sebagai nol.`}/>} 
 {data?.status==='AVAILABLE'&&data.hierarchy?.[0]&&<><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-medium text-slate-700">{data.comparisonLabel}</p><p className="text-xs text-slate-500">Nilai analitis read-only dari Engine 2 V2 · Lineage {data.analysisLineageKey?.slice(0,16)}…</p></div><a className="flex items-center gap-2 rounded-lg bg-emerald-700 px-4 py-2 text-sm font-medium text-white" href={`/api/cost-fluctuation/export?periodId=${periodId}&comparison=${comparison}`}><Download className="h-4 w-4"/>Export Excel</a></div><AnalysisSummary root={data.hierarchy[0]} commentaries={data.commentaries}/><AnalysisTreeTable nodes={visible} commentaries={data.commentaries} onCommentary={setSelected}/></>}
 {selected&&<div className="fixed inset-0 z-50 flex justify-end bg-slate-950/40" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><div className="h-full w-full overflow-y-auto bg-slate-50 p-4 shadow-2xl sm:max-w-xl"><button className="ml-auto flex items-center gap-1 p-2 text-sm" onClick={()=>setSelected(null)}><X className="h-4 w-4"/>Tutup</button>{message&&<p className="mb-3 rounded border bg-white p-3 text-sm">{message}</p>}<CommentaryEditor key={`${selected.key}:${current?.id??'new'}:${current?.status??'OPEN'}`} analysisKey={selected.key} commentary={current} suggestedText={selected.suggestedCommentary?.text} permissions={permissions} currentUserId={currentUserId} busy={loading} onAction={action} context={<div className="grid grid-cols-2 gap-2 rounded bg-slate-100 p-3 text-sm"><strong className="col-span-2">{selected.label}</strong><span>Current: {formatIdr(selected.currentAmount)}</span><span>Comparison: {formatIdr(selected.comparisonAmount)}</span><span>Variance: {formatIdr(selected.varianceAmount)}</span><span>Variance %: {formatPercent(selected.variancePercent,selected.variancePercentStatus)}</span></div>}/></div></div>}
 </section>
}
function Notice({icon,text}:{icon:'info'|'integrity'|'error';text:string}){const Icon=icon==='info'?Info:icon==='integrity'?ShieldAlert:AlertTriangle;const tone=icon==='info'?'border-blue-200 bg-blue-50 text-blue-800':icon==='integrity'?'border-red-300 bg-red-50 text-red-800':'border-amber-300 bg-amber-50 text-amber-900';return <div role={icon==='info'?'status':'alert'} className={`flex items-start gap-3 rounded-xl border p-4 ${tone}`}><Icon className="mt-0.5 h-5 w-5 shrink-0"/><p className="text-sm">{text}</p></div>}
