'use client';
import { FormEvent, useCallback, useMemo, useState } from 'react';
import { explainMaterialityRule } from '@/lib/cost-fluctuation/governance/presentation';

type Master = { id: number; companyCode: string; costGroups: Array<{ id: number; code: string; name: string }> };
type Rule = { id:number; active:boolean; comparisonType:string; amountThreshold:string|null; percentThreshold:string|null; operator:'AND'|'OR'; validFrom:string; validTo:string|null; company:{id:number;companyCode:string}; costGroup:{id:number;code:string}|null };
type Fields = { amount: string; percent: string; operator: 'AND'|'OR' };
const initial: Fields = { amount: '', percent: '', operator: 'OR' };

function ThresholdFields({ value, onChange }: { value: Fields; onChange: (next: Fields) => void }) {
  return <><label className="text-sm font-medium">Amount threshold<input name="amountThreshold" inputMode="decimal" value={value.amount} onChange={(e)=>onChange({...value,amount:e.target.value})} placeholder="No default" className="mt-1 block w-full rounded border p-2"/></label><label className="text-sm font-medium">Percentage threshold<input name="percentThreshold" inputMode="decimal" value={value.percent} onChange={(e)=>onChange({...value,percent:e.target.value})} placeholder="20 means 20%" className="mt-1 block w-full rounded border p-2"/></label><label className="text-sm font-medium">Criteria operator<select name="operator" value={value.operator} onChange={(e)=>onChange({...value,operator:e.target.value as 'AND'|'OR'})} className="mt-1 block w-full rounded border p-2"><option value="OR">OR — either criterion</option><option value="AND">AND — both criteria</option></select></label><p className="rounded bg-slate-50 p-3 text-sm md:col-span-3"><strong>Preview:</strong> {explainMaterialityRule(value.amount,value.percent,value.operator)}</p></>;
}

export default function MaterialityRuleAdmin({ masters, initialRules }: { masters: Master[]; initialRules: Rule[] }) {
  const [rules,setRules]=useState<Rule[]>(initialRules), [error,setError]=useState(''), [success,setSuccess]=useState(''), [successor,setSuccessor]=useState<Rule|null>(null), [companyId,setCompanyId]=useState(''), [fields,setFields]=useState(initial), [successorFields,setSuccessorFields]=useState(initial), [showHistory,setShowHistory]=useState(false);
  const load=useCallback(async()=>{const response=await fetch('/api/cost-fluctuation/materiality-rules');const body=await response.json();if(!response.ok)throw new Error(body.error??'Unable to load rules.');setRules(body.rules);},[]);
  const groups=useMemo(()=>masters.find((company)=>String(company.id)===companyId)?.costGroups??[],[companyId,masters]);
  async function send(path:string, form:HTMLFormElement){setError('');setSuccess('');const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const body=await response.json();if(!response.ok)throw new Error(body.error??'Request failed.');await load();setSuccessor(null);setFields(initial);setSuccessorFields(initial);setSuccess(path.includes('successor')?'Successor created. The predecessor remains in history.':'Effective rule created.');}
  async function submit(event:FormEvent<HTMLFormElement>, path:string){event.preventDefault();try{await send(path,event.currentTarget);}catch(reason){setError(reason instanceof Error?reason.message:'Request failed.');}}
  const visible=rules.filter((rule)=>showHistory||rule.active);
  return <div className="space-y-5">{error&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-red-700">{error}</p>}{success&&<p className="rounded border border-green-300 bg-green-50 p-3 text-green-800">{success}</p>}
    <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><strong>NOT_CONFIGURED is a valid, blocking state.</strong> Create a rule only from approved business thresholds. This screen never supplies arbitrary defaults.</div>
    <form onSubmit={(event)=>submit(event,'/api/cost-fluctuation/materiality-rules')} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-3"><h2 className="text-lg font-semibold md:col-span-3">New effective rule</h2><label className="text-sm font-medium">Company<select required name="companyId" value={companyId} onChange={(e)=>setCompanyId(e.target.value)} className="mt-1 block w-full rounded border p-2"><option value="">Select company</option>{masters.map(c=><option key={c.id} value={c.id}>{c.companyCode}</option>)}</select></label><label className="text-sm font-medium">Cost Group scope<select name="costGroupId" disabled={!companyId} className="mt-1 block w-full rounded border p-2"><option value="">Company fallback (all groups)</option>{groups.map(g=><option key={g.id} value={g.id}>{g.code} — {g.name}</option>)}</select></label><label className="text-sm font-medium">Comparison<select name="comparisonType" className="mt-1 block w-full rounded border p-2"><option>MOM</option><option>YOY</option><option>YTD</option></select></label><ThresholdFields value={fields} onChange={setFields}/><label className="text-sm font-medium">Effective from<input required type="date" name="validFrom" className="mt-1 block w-full rounded border p-2"/></label><label className="text-sm font-medium">Effective to (optional)<input type="date" name="validTo" className="mt-1 block w-full rounded border p-2"/></label><button className="self-end rounded bg-blue-700 p-2 text-white">Create effective rule</button></form>
    {successor&&<form onSubmit={(event)=>submit(event,`/api/cost-fluctuation/materiality-rules/${successor.id}/successor`)} className="grid gap-3 rounded-xl border border-blue-200 bg-blue-50 p-5 md:grid-cols-3"><div className="md:col-span-3"><h2 className="text-lg font-semibold">Successor to rule #{successor.id}</h2><p className="text-sm">Locked scope: {successor.company.companyCode} / {successor.costGroup?.code??'company fallback'} / {successor.comparisonType}. The historical rule is end-dated, never edited in place.</p></div><ThresholdFields value={successorFields} onChange={setSuccessorFields}/><label className="text-sm font-medium">Successor effective from<input required type="date" name="validFrom" className="mt-1 block w-full rounded border p-2"/></label><label className="text-sm font-medium">Effective to (optional)<input type="date" name="validTo" className="mt-1 block w-full rounded border p-2"/></label><div className="flex items-end gap-2"><button className="rounded bg-blue-700 px-3 py-2 text-white">Create successor</button><button type="button" className="rounded border bg-white px-3 py-2" onClick={()=>setSuccessor(null)}>Cancel</button></div></form>}
    <div className="rounded-xl border bg-white"><div className="flex items-center justify-between p-4"><h2 className="font-semibold">Current and historical rules</h2><label className="text-sm"><input type="checkbox" checked={showHistory} onChange={(e)=>setShowHistory(e.target.checked)} className="mr-2"/>Show superseded/history</label></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Status</th><th>Scope</th><th>Comparison</th><th>Rule</th><th>Effective interval</th><th>Action</th></tr></thead><tbody>{visible.map(rule=><tr key={rule.id} className="border-t"><td className="p-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${rule.active?'bg-emerald-100 text-emerald-800':'bg-slate-100 text-slate-600'}`}>{rule.active?'CURRENT':'SUPERSEDED'}</span></td><td>{rule.company.companyCode} / {rule.costGroup?.code??'All groups fallback'}</td><td>{rule.comparisonType}</td><td>{rule.amountThreshold??'—'} {rule.operator} {rule.percentThreshold?`${rule.percentThreshold}%`:'—'}</td><td>{rule.validFrom.slice(0,10)} – {rule.validTo?.slice(0,10)??'open-ended'}</td><td>{rule.active&&<button className="rounded border px-2 py-1" onClick={()=>{setSuccessor(rule);setSuccessorFields({amount:rule.amountThreshold??'',percent:rule.percentThreshold??'',operator:rule.operator});}}>Create successor</button>}</td></tr>)}</tbody></table>{!visible.length&&<p className="p-5 text-sm text-slate-500">No rules. Materiality remains NOT_CONFIGURED until approved thresholds are entered.</p>}</div></div>
  </div>;
}
