'use client';
import { FormEvent, useCallback, useEffect, useState } from 'react';

type Rule = { id:number; active:boolean; comparisonType:string; amountThreshold:string|null; percentThreshold:string|null; operator:string; validFrom:string; validTo:string|null; company:{companyCode:string}; costGroup:{code:string}|null };

export default function MaterialityRuleAdmin() {
  const [rules,setRules]=useState<Rule[]>([]), [error,setError]=useState(''), [success,setSuccess]=useState(''), [successor,setSuccessor]=useState<Rule|null>(null);
  const load=useCallback(async()=>{const response=await fetch('/api/cost-fluctuation/materiality-rules');const body=await response.json();if(!response.ok)throw new Error(body.error??'Unable to load rules.');setRules(body.rules);},[]);
  useEffect(()=>{let ignore=false;void fetch('/api/cost-fluctuation/materiality-rules').then(async response=>({response,body:await response.json()})).then(({response,body})=>{if(ignore)return;if(!response.ok)throw new Error(body.error??'Unable to load rules.');setRules(body.rules);}).catch((reason:unknown)=>{if(!ignore)setError(reason instanceof Error?reason.message:'Unable to load rules.');});return()=>{ignore=true;};},[]);
  async function send(path:string, form:HTMLFormElement){setError('');setSuccess('');const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const body=await response.json();if(!response.ok)throw new Error(body.error??'Request failed.');await load();form.reset();setSuccessor(null);setSuccess(path.includes('successor')?'Successor created; predecessor history was preserved.':'Rule created.');}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();try{await send('/api/cost-fluctuation/materiality-rules',event.currentTarget);}catch(reason){setError(reason instanceof Error?reason.message:'Rule creation failed.');}}
  async function createSuccessor(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!successor)return;try{await send(`/api/cost-fluctuation/materiality-rules/${successor.id}/successor`,event.currentTarget);}catch(reason){setError(reason instanceof Error?reason.message:'Successor creation failed.');}}
  const fields=<><input name="amountThreshold" placeholder="Amount threshold" className="rounded border p-2"/><input name="percentThreshold" placeholder="Percent threshold (20 = 20%)" className="rounded border p-2"/><select name="operator" className="rounded border p-2"><option>OR</option><option>AND</option></select></>;
  return <div className="space-y-5">{error&&<p className="rounded border border-red-300 bg-red-50 p-3 text-red-700">{error}</p>}{success&&<p className="rounded border border-green-300 bg-green-50 p-3 text-green-800">{success}</p>}
    <form onSubmit={create} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-3"><input required name="companyId" placeholder="Company ID" className="rounded border p-2"/><input name="costGroupId" placeholder="Cost Group ID (optional)" className="rounded border p-2"/><select name="comparisonType" className="rounded border p-2"><option>MOM</option><option>YOY</option><option>YTD</option></select>{fields}<input required type="date" name="validFrom" className="rounded border p-2"/><input type="date" name="validTo" className="rounded border p-2"/><button className="rounded bg-blue-700 p-2 text-white">Create effective rule</button></form>
    {successor&&<form onSubmit={createSuccessor} className="grid gap-3 rounded-xl border border-blue-200 bg-blue-50 p-5 md:grid-cols-3"><div className="md:col-span-3"><strong>Create successor for #{successor.id}</strong><p className="text-sm text-slate-600">Scope remains {successor.company.companyCode}/{successor.costGroup?.code??'ALL'}/{successor.comparisonType}. The existing rule remains historical and will only be end-dated.</p></div>{fields}<input required type="date" name="validFrom" aria-label="Successor valid from" className="rounded border p-2"/><input type="date" name="validTo" aria-label="Successor valid to" className="rounded border p-2"/><div className="flex gap-2"><button className="rounded bg-blue-700 px-3 text-white">Create successor</button><button type="button" className="rounded border px-3" onClick={()=>setSuccessor(null)}>Cancel</button></div></form>}
    <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead><tr><th>ID</th><th>Scope</th><th>Comparison</th><th>Amount</th><th>Percent</th><th>Operator</th><th>Effective</th><th>Action</th></tr></thead><tbody>{rules.map(rule=><tr key={rule.id} className="border-t text-center"><td>{rule.id}</td><td>{rule.company.companyCode}/{rule.costGroup?.code??'ALL'}</td><td>{rule.comparisonType}</td><td>{rule.amountThreshold??'—'}</td><td>{rule.percentThreshold??'—'}</td><td>{rule.operator}</td><td>{rule.validFrom.slice(0,10)} – {rule.validTo?.slice(0,10)??'open'}</td><td>{rule.active&&<button className="rounded border px-2 py-1" onClick={()=>{setSuccessor(rule);setError('');setSuccess('');}}>Create Successor</button>}</td></tr>)}</tbody></table></div>
  </div>;
}
